In [1]:
import numpy as np
print(np.__version__)

2.3.1


In [ ]:
import numpy as np
arr=np.zeros(5)
print(arr)
arr.dtype
arr.astype(np.int32)

[0. 0. 0. 0. 0.]


array([0, 0, 0, 0, 0], dtype=int32)

In [66]:
arr1=np.ones(5,dtype="int")
print(arr1)
print(arr1.dtype)
print(arr1.shape)

[1 1 1 1 1]
int64
(5,)


In [67]:
arr=np.array([[10,2,30],[4,50,6],[70,8,9],[101,11,12]])
print("Array",arr)
print("Shape",arr.shape)
print("datatype",arr.dtype)

Array [[ 10   2  30]
 [  4  50   6]
 [ 70   8   9]
 [101  11  12]]
Shape (4, 3)
datatype int64


In [68]:
print("swapaxes",np.swapaxes(arr,0,1)) #to interchange the axis, row become column ,column become row

swapaxes [[ 10   4  70 101]
 [  2  50   8  11]
 [ 30   6   9  12]]


In [57]:
print("Reshape array",arr.reshape(3,4)) #reaarange columns

Reshape array [[ 10   2  30   4]
 [ 50   6  70   8]
 [  9 101  11  12]]


In [70]:
print("Sort in axis=0",np.sort(arr,axis=0))
print("Sort in axis=1",np.sort(arr,axis=1))

Sort in axis=0 [[  4   2   6]
 [ 10   8   9]
 [ 70  11  12]
 [101  50  30]]
Sort in axis=1 [[  2  10  30]
 [  4   6  50]
 [  8   9  70]
 [ 11  12 101]]


In [59]:
print("max element",np.max(arr)) #gives max element

max element 101


In [ ]:
np.linspace(1,10,num=5) #creating range between array

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [69]:
arr1=np.zeros((4,3),dtype="int")
print(arr1)
print(arr1.shape)
print("Datatype of array",arr1.dtype)
print("Size of array",arr1.size)


[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
(4, 3)
Datatype of array int64
Size of array 12
