In [ ]:
# can create array of n dimensional
# indexing ,stored in continous order in mry
# homogenous data, arange,ndim,reshape creating array with dimensions,shape,size,adding 2 array
# image processing,argmax,argmin   1,2,3 d
# ?array1   doc string (what it is doing)anything to seacrch

In [1]:
#importing libraries
import numpy as np

In [23]:
#creating 1D array
array1=np.array([29,19,24,10,40])
print(array1)
print(array1.ndim) #number of dimensions
print(array1.dtype) #datatype of array
print(array1.size) #size of array

[29 19 24 10 40]
1
int64
5


In [14]:
#creating 2D array
array2=np.array([[10,30,50],[20,40,60]])
print(array2) 
print(array2.ndim) #number of dimensions
print(array2.shape) #shape of array
print(array2.dtype) #datatype of array
print(array2.size) #size of array

[[10 30 50]
 [20 40 60]]
2
(2, 3)
int64
6


In [16]:
#creating 3D array
array3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array3)
print(array3.ndim) #number of dimensions    
print(array3.shape) #shape of array
print(array3.dtype) #datatype of array
print(array3.size) #size of array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
int64
12


In [ ]:
#indexing of array
print(array1[0]) #retrieve 1st element
print(array1[-1]) #retrieve last element
print(array1)
print(array1[0:2]) #slicing array


29
40
[29 19 24 10 40]
[29 19]


In [ ]:
#creating an array with arange
array=np.arange(1,11) #array with values from 1 to 10
print(array)
print(array.ndim) #number of dimensions
print(array.size) #size of array
print(array.dtype) #datatype of array

[ 1  2  3  4  5  6  7  8  9 10]
1
10
int64


In [41]:
#reshaping array
array_re=array.reshape(5,2) #reshaping array to 5 rows and 2 columns
print(array_re)
print(array_re.ndim) #number of dimensions
print(array_re.shape) #shape of array

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2
(5, 2)


In [50]:
#arithmetic operations on arrays
x=np.array([10,20,30])
y=np.array([20,40,60])
print("Addition",x+y) #adding 2 arrays
print("Substraction",x-y) #subtracting 2 arrays
print("Multiplication",x*y) #multiplying 2 arrays
print("Division",x/y) #dividing 2 arrays 
print("Square",x**y) #square of array elements
print("Power",x**2) #power of array elements

Addition [30 60 90]
Substraction [-10 -20 -30]
Multiplication [ 200  800 1800]
Division [0.5 0.5 0.5]
Square [7766279631452241920                   0 1152921504606846976]
Power [100 400 900]


In [54]:
?np

Type:        module
String form: <module 'numpy' from 'c:\\Users\\SAINATH\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\sainath\appdata\local\programs\python\python313\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snip

In [52]:
#use of argmax and argmin
print(array1)
print(array1.max())  # maximum value in the array
print(array1.min())  # minimum value in the array
print("Index of max value:", np.argmax(array1))   # index of maximum value
print("Index of min value:", np.argmin(array1))   # index of minimum value

[29 19 24 10 40]
40
10
Index of max value: 4
Index of min value: 3


In [45]:
#diff between elements
arr = np.array([1, 3, 6, 10])
diff_arr = np.diff(arr) #difference between consecutive elements in an array.
print(diff_arr) 

[2 3 4]


In [51]:
#linespace in array
l_arr = np.linspace(1, 5, num=6) #generating evenly spaced values
print(l_arr)  


[1.  1.8 2.6 3.4 4.2 5. ]


In [53]:
?array1

Type:        ndarray
String form: [29 19 24 10 40]
Length:      5
File:        c:\users\sainath\appdata\local\programs\python\python313\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : 